app/controllers/discourse_code_review/code_review_controller.rb
assets/javascripts/discourse/activity-route-map.js.es6
assets/javascripts/discourse/routes/user-activity-approval-given.js.es6
assets/javascripts/discourse/routes/user-activity-approval-pending.js.es6
assets/javascripts/discourse/templates/connectors/user-activity-bottom/commit-activity-link.hbs
assets/javascripts/discourse/widgets/code-review-commit-approved-notification-item.js.es6
config/locales/client.en.yml
plugin.rb
spec/requests/discourse_code_review/code_review_controller_spec.rb

These changes add approved notifications for commit authors and placate the pesky unread indicator for everyone else.
This PR relies on changes to discourse core: https://github.com/discourse/discourse/pull/7725 and https://github.com/discourse/discourse/pull/7727

FEATURE: Approved notifications

---

assets/javascripts/discourse/widgets/code-review-commit-approved-notification-item.js.es6

Related to discourse/discourse#7840.

FIX: Rename overridden title method.

---

plugin.rb

This gem is already in core, and the versions are conflicting, so there is no reason to have it here.

DEV: remove public_suffix gem dependency

---

plugin.rb
spec/discourse_code_review/lib/github_pr_syncer_spec.rb
spec/plugin_spec.rb

`DiscourseCodeReview::GithubPRSyncer#mirror_pr_post` already behaved this way.
This PR updates `DiscourseCodeReview#sync_post_to_github`.

FEATURE: Send only regular posts to GitHub

---

lib/discourse_code_review/github_pr_syncer.rb
spec/lib/github_pr_syncer_spec.rb

`topic.category` is always `nil` if the topic is a PM.

FIX: Don't mirror PR if the post is from a PM

---

lib/discourse_code_review/importer.rb

Example [here](https://github.com/discourse/discourse/pull/10709)
If someone opens a PR to merge a fork's commit into the main repo, and someone comments on the commit instead of the PR, the plugin won't be able to find it.

FIX: Don't try to sync a commit if it's not present in the main repo.

---

app/controllers/discourse_code_review/code_review_controller.rb
spec/requests/discourse_code_review/code_review_controller_spec.rb

If you had all code review categories muted, then previously you would be taken to `/latest` every time you review a commit. Now it will continue in the same category, even if it's muted.

FEATURE: Continue reviewing in same category, even if muted

---

app/controllers/discourse_code_review/code_review_controller.rb
assets/javascripts/discourse/initializers/init-code-review.js.es6
config/locales/server.en.yml
config/settings.yml
spec/requests/discourse_code_review/code_review_controller_spec.rb

The followup button can be handy in many cases, but it can also create lots
of broken windows where commits sit in limbo for many months or even years.
This allows opting out of this button by setting
`code_review_allow_manual_followup` to false in site setting
Default behavior is not impacted

FEATURE: allow removal of followup button

---

lib/discourse_code_review/github_repo.rb
lib/discourse_code_review/state/commit_topics.rb
spec/discourse_code_review/lib/importer_spec.rb

For example, if word follow is found before a commit hash, the system
will automatically interpret it as a follow up commit. Before this, a
proper Git trailer was needed such as:
> Follow-up-to: 5ff6c10320cab7ef82ecda40c57cfb9e539b7e72
Now, the whole message body can be just:
> Minor follow-up bug fix for 5ff6c10.

FEATURE: Allow for less restrictive follow up commit mentioning

---

app/controllers/discourse_code_review/code_review_controller.rb
assets/javascripts/discourse/initializers/init-code-review.js.es6
config/locales/client.en.yml
plugin.rb
spec/requests/discourse_code_review/code_review_controller_spec.rb

This button can be used by the original author, after they followed up,
to remove assignment and move it back into the pending queue.

FEATURE: Add "Followed Up" button

---

lib/discourse_code_review/state/commit_approval.rb
spec/discourse_code_review/lib/state/commit_approval_spec.rb

GitHub allows the same user to approve the same pull request multiple
times.

FIX: Make sure approvers are unique

---

lib/discourse_code_review/state/helpers.rb

This ensures that old commits that are newly applied at shown in topic
lists as expected.

DEV: Set the bumped_at time whenever we create a new topic

---

config/settings.yml

Don't display API Key by default, require logged click

Make API Key secret

---

app/controllers/discourse_code_review/code_review_controller.rb

There were reports of `code_review_sync_commits` being called with a blank of `repo_name`, but none of the GitHub webhook logs show any payload with an empty repo `full_name`.

DEV: Print debug info if repo_name is blank

---

app/controllers/discourse_code_review/code_review_controller.rb
app/jobs/regular/code_review_sync_commit_comments.rb
app/jobs/regular/code_review_sync_commits.rb
lib/discourse_code_review/github_pr_syncer.rb
lib/discourse_code_review/github_repo.rb
lib/discourse_code_review/importer.rb
lib/discourse_code_review/state/github_repo_categories.rb
plugin.rb
spec/discourse_code_review/lib/state/github_repo_categories_spec.rb

When a repository is moved or renamed the plugin creates a new category on subsequent commit because the category is identified by repository full_name (`{github_org}/{github_repo}`). This commit links the category to repository ID so that when the repository full_name is changed it can find the category via repository ID. It also updates the repository full_name to reflect new location/name.

FIX: find existing category when a repository is moved/renamed

---

lib/discourse_code_review/state/github_repo_categories.rb
spec/discourse_code_review/lib/github_pr_syncer_spec.rb
spec/discourse_code_review/lib/github_repo_spec.rb
spec/discourse_code_review/lib/importer_spec.rb
spec/discourse_code_review/lib/state/github_repo_categories_spec.rb
spec/jobs/code_review_sync_commits_spec.rb

This commit prevents creation of duplicate code-review categories.

FIX: only create new category when repo_id is present

---

lib/discourse_code_review/state/commit_topics.rb

Before this fix a very long title would bypass validation (as we use skip_validations: true) and would then fail in the database insert as fancy_title is `character varying(400)`
```
ActiveRecord::ValueTooLong: PG::StringDataRightTruncation: ERROR:  value too long for type character varying(400)
```

FIX: ensures we are not attempting to store a too ling title

---

lib/discourse_code_review/state/commit_topics.rb

It avoid calling `Topic.fancy_title` two times, it works because Topic.fancy_title(title) when under limit with mostly return a safe version of title

DEV: simplify truncation logic

---

lib/discourse_code_review/state/commit_topics.rb

Given the automatic nature of this post creation, we can't ask user to modify input and have to do it ourselves beforehand.

FIX: brute force title length until it works for fancy_title max length

---

lib/discourse_code_review/source/git_repo.rb
plugin.rb
spec/discourse_code_review/lib/github_repo_spec.rb
spec/helpers/integration.rb
spec/lib/tasks/code_review_sha_backfill_spec.rb

Updates `rugged` (and fixes a breaking change introduced in ~1.1), `octokit`, and `graphql`.
Also changes `master` branch to `main` in specs, and captures output in specs.

DEV: Update `rugged` and other deps

---

config/locales/server.en.yml

For some reason I did not include these in the original
commit at
https://github.com/discourse/discourse-code-review/commit/40423c19f45fd22240c530b958913d4e95a5f7ad.

FIX: Translations for bad_github_X were missing

---

plugin.rb
spec/requests/discourse_code_review/repos_controller_spec.rb

Rails does not allow dots in route params by default.
This can be allowed using a route constraint. I used the
same one we use for usernames in core. Without this,
a 404 error is raised on has_webhooks for any repo with
a . in the name.

FIX: Allow dots in repo names

---

spec/requests/discourse_code_review/code_review_controller_spec.rb

`TopicUser#highest_seen_post_number` is being removed in the near near
future.
See https://github.com/discourse/discourse/pull/13471

DEV: Remove redundant test.

---

plugin.rb

It's now included by default in core. Having it declared here makes updating it difficult. See: https://github.com/discourse/discourse/pull/13625

DEV: Remove `addressable` dependency

---

lib/discourse_code_review/state/commit_topics.rb
spec/discourse_code_review/lib/importer_spec.rb

The commit message is converted to HTML and back to Markdown to link
other commits. When this happened, Emojis were converted to img HTML
tags and then to image Markdown. This commit disables emojis parser to
make sure no images are inserted in commit message.

FIX: Do not parse emoji in commit message

---

plugin.rb

Using procs lets us pass additional arguments to the function without breaking existing ones.

DEV: Use Procs instead of lambdas for the consolidation rule.

---

lib/discourse_code_review/state/commit_approval.rb
plugin.rb

Since we changed how the approved commit notification consolidation works, we no longer delete previous notifications after creating a consolidated one. This revealed a race condition where we create duplicated notifications, consolidating it into itself:
To fix this, this commit makes the approved tag check atomic using a mutex.

FIX: Don't duplicate notifications if receiving duplicate webhooks.

---

app/models/github_repo_category.rb
db/migrate/20220111185133_create_code_review_github_repos.rb
lib/discourse_code_review/github_pr_syncer.rb
lib/discourse_code_review/state/github_repo_categories.rb
plugin.rb
spec/discourse_code_review/lib/state/github_repo_categories_spec.rb

This version still writes the data to custom fields for easier
reversion, just in case.

DEV: Prefer tables over custom fields, github categories, step 1

---

app/controllers/discourse_code_review/code_review_controller.rb
app/models/commit_topic.rb
db/migrate/20220111185242_create_code_review_commit_topics.rb
lib/discourse_code_review/github_pr_syncer.rb
lib/discourse_code_review/rake_tasks.rb
lib/discourse_code_review/state/commit_topics.rb
plugin.rb
spec/discourse_code_review/lib/state/commit_topics_spec.rb
spec/lib/tasks/code_review_sha_backfill_spec.rb
spec/plugin_spec.rb
spec/requests/discourse_code_review/code_review_controller_spec.rb

This version still writes the data to custom fields for easier
reversion, just in case.

DEV: Prefer tables over custom fields, commit topics, part 1

---

plugin.rb

As we’re upgrading Discourse to Rails 7.0.1, the way the autoloader was working previously changed a bit. We have weird stuff in some places like requiring files from `lib/` with the `lib` prefix which shouldn’t happen.
As the current version of Discourse already autoloads its `lib` folder, the `require_dependency` calls we have in this plugin aren’t useful anymore.
This patch removes these calls which leaves the plugin compatible with the current version of Discourse and makes it compatible with the changes that are going to be introduced when upgrading to Rails 7.0.1.
----
Rails 7 upgrade PR for reference: https://github.com/discourse/discourse/pull/15649 (WIP at the time of writing)

DEV: Add compatibility for Rails 7.0+

---

lib/discourse_code_review/state/commit_topics.rb
spec/discourse_code_review/lib/importer_spec.rb

Previous regex matched last paragraphs with ':' or '=' on every line.
This new regex checks if all lines from the last paragraph have a word,
the separator ': ' and another string.

FIX: Be more strict when matching Git trailers

---

plugin.rb

Reusing GraphQL and Octokit instances is not thread safe.

FIX: Do not reuse GraphQL clients

---

spec/discourse_code_review/lib/github_repo_spec.rb
spec/helpers/remote_mocks.rb

```
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
```

DEV: Use `setup_git_repo` helper to avoid warnings

---

app/controllers/discourse_code_review/repos_controller.rb
spec/requests/discourse_code_review/repos_controller_spec.rb

The plugin returned a 500 because of an unhandled exception.

FIX: Show error if plugin is not configured

---

lib/discourse_code_review/state/commit_topics.rb
spec/discourse_code_review/lib/state/commit_topics_spec.rb

It used to not work if a commit's topic was deleted and then the same
commit was imported again.

FIX: Allow deleted topics to be imported again

---

app/controllers/discourse_code_review/code_review_controller.rb
app/jobs/regular/code_review_sync_commits.rb
config/settings.yml
lib/discourse_code_review/github_pr_syncer.rb

After an approved PR is merged the commit topic that is created for the
associated commit is sometimes not automatically approved. We originally
thought it was a race condition because of reused Octokit client
instances, but that was not the problem. The additional debug
information will give more insight about what is happening inside the
auto approval process.

DEV: Log debug info about auto GitHub approvals

---

assets/javascripts/discourse/templates/connectors/user-activity-bottom/approval-given-button.hbs
assets/javascripts/discourse/templates/connectors/user-activity-bottom/approval-pending-button.hbs

Previously these were in the same connector, which meant they shared a parent `li` (the connector class). The shared `li` parent meant that hovering over one made them both get the hover state.
This commit separates them and eliminates the issue.
Before:
After:

UX: separate profile buttons to fix hover state

---

lib/discourse_code_review/state/commit_topics.rb
spec/discourse_code_review/lib/importer_spec.rb

The previous regular expression looked for Git trailers in the whole
commit message, not only in the last paragraph. For example, it escaped
the last paragraph if the first paragraph was "foo: bar".

FIX: Escape Git trailers present in last paragraph

---

app/controllers/discourse_code_review/code_review_controller.rb
app/jobs/regular/code_review_sync_commits.rb

Some commits are not automatically approved even if they follow all the
requirements necessary for that. Running the same sync process again at
a later time seems to work as expected.
This commits adds a 30 seconds delay between the time the merge webhook
is received and the time the sync process happens. If this is just a
timing issue, this delay should fix that.

FIX: Wait 30 seconds before syncing commits

---

assets/javascripts/discourse/components/review-topic-list-item.js

Context: https://deprecations.emberjs.com/v3.x/#toc_ember-string-prototype_extensions

DEV: Remove 'htmlSafe' string prototype extensions

---

lib/discourse_code_review/state/commit_topics.rb
spec/discourse_code_review/lib/importer_spec.rb

Git trailers must start exactly at the beginning of the line.

FIX: Make Git trailers parsing stricter

---

app/controllers/discourse_code_review/code_review_controller.rb
assets/javascripts/discourse/initializers/init-code-review.js
lib/discourse_code_review/github_pr_syncer.rb
lib/discourse_code_review/state/commit_approval.rb
plugin.rb
spec/plugin_spec.rb
test/javascripts/acceptance/self-approve-desktop-test.js
test/javascripts/acceptance/self-approve-mobile-test.js

`CurrentUserSerializer` in core has a `can_review` attribute that's used to check if the user can see the Review link in the hamburger menu:
https://github.com/discourse/discourse/blob/010bb20f53cc81068824fc278c457ef1739f25e7/app/serializers/current_user_serializer.rb#L263-L265
However, this plugin adds an attribute with the same name to the serializer which overrides (inadvertently) core's definition of the attribute and results in issues such as users not being able to see the Review link if the plugin is disabled. This PR renames `can_review` to `can_review_code` everywhere in the plugin to avoid conflicts with core.

FIX: Rename `can_review` to `can_review_code`

---

assets/javascripts/discourse/initializers/init-code-review.js
assets/javascripts/discourse/widgets/code-review-commit-approved-notification-item.js
config/locales/client.ar.yml
config/locales/client.de.yml
config/locales/client.en.yml
config/locales/client.es.yml
config/locales/client.fi.yml
config/locales/client.fr.yml
config/locales/client.he.yml
config/locales/client.it.yml
config/locales/client.ja.yml
config/locales/client.pt_BR.yml
config/locales/client.ru.yml
config/locales/client.sv.yml
config/locales/client.zh_CN.yml
test/javascripts/acceptance/commit-approved-notifications-test.js

This PR ports the widgets-based implementation of the `code_review_commit_approved` notification item to the experimental Glimmer-based user menu. The changes in this PR should make `code_review_commit_approved` notifications in the experimental user menu consistent with they look/behave in the old user menu.
We don't need to add a `.discourse-compatibility` entry for this change because it's fully backward compatible since we check that the `registerNotificationTypeRenderer` plugin API is available before we attempt to use it.
For more context on the experimental user menu, see https://github.com/discourse/discourse/pull/17379.

DEV: Add support for the experimental user menu

---

assets/javascripts/discourse/initializers/init-code-review.js
test/javascripts/acceptance/commit-approved-notifications-test.js

`fancy_title` is sanitized/escaped by the server and is safe to render as HTML, so can opt-out of escaping it when it's rendered inside notifications in the experimental user menu to avoid characters like `'><&` getting incorrectly escaped.
Follow-up to https://github.com/discourse/discourse-code-review/commit/191af9e9e3efa83835751ef952a4a67ef915cfa0.

DEV: Don't double-escape fancy title in commit approved notifications

---

test/javascripts/acceptance/admin-webhook-configuration-test.js

These tests rely on a dialog in core that is about to change in https://github.com/discourse/discourse/pull/18292. So, to get stuff passing in CI and builds, I'm following this process: 
- skipping the tests (this PR)
- getting the core PR to ✅ in CI
- merging core PR
- reverting the skip and adjusting the test in code-review

DEV: Temporarily skip two tests

---

app/jobs/regular/code_review_sync_commits.rb
app/jobs/scheduled/code_review_sync_repos.rb
lib/discourse_code_review/github_repo.rb
plugin.rb
spec/helpers/github_rest_api_mock.rb
spec/helpers/integration.rb
spec/jobs/code_review_sync_commits_spec.rb
spec/jobs/code_review_sync_repos_spec.rb

If any of the webhooks were lost because the site was unavailable
(networking issues, site update, etc) then the commit would not be
synced until another was pushed.
The new job ensures that all repositories are synced at least once an
hour.

FIX: Periodically resync repos

---

assets/javascripts/discourse/templates/connectors/user-activity-bottom/approval-given-button.hbs
assets/javascripts/discourse/templates/connectors/user-activity-bottom/approval-pending-button.hbs

The plugin outlet is already wrapped in a `li` tag
https://github.com/discourse/discourse/blob/c0037dc0f06f08bd050aedc8aad97d1f05b322ab/app/assets/javascripts/discourse/app/templates/user/activity.hbs#L69

UX: Remove unnecessary `li` tag for user-activity-bottom plugin outlet

---

app/jobs/regular/code_review_sync_commits.rb

This logged a warning everytime that happened, but it is normal for deleted or archived topics.

DEV: Return early if remote commit cannot be found

---

lib/discourse_code_review/state/github_repo_categories.rb
plugin.rb
spec/discourse_code_review/lib/state/github_repo_categories_spec.rb

This commit ensures the repository category is recreated if it was destroyed.

FIX: Recreate repo category if it was deleted

---

app/controllers/discourse_code_review/code_review_controller.rb
app/jobs/regular/code_review_sync_commit_comments.rb
app/jobs/regular/code_review_sync_pull_request.rb
plugin.rb
spec/requests/discourse_code_review/code_review_controller_spec.rb

Processing webhooks can fail sometimes (GitHub API rate limits, networking issues, etc) and without a retry mechanism, the payload is lost and the event is not processed properly. Sidekiq provides automatic retry functionality that can be used to retry payload processing.

DEV: Use jobs to process webhook payload

---

app/jobs/regular/code_review_sync_commit_comments.rb
app/jobs/regular/code_review_sync_commits.rb
app/jobs/regular/code_review_sync_pull_request.rb
lib/octokit_rate_limit_retry_mixin.rb
plugin.rb
spec/lib/octokit_rate_limit_retry_mixin_spec.rb

It used default Sidekiq logic which retries several times without taking into account GitHub API rate limit.

FIX: Retry after rate limit is lifted

---

app/controllers/discourse_code_review/code_review_controller.rb
spec/requests/discourse_code_review/code_review_controller_spec.rb

Using old repository names can lead to invalid GraphQL queries and result in errors.

FIX: Update repository name when receiving webhook

---

spec/lib/octokit_rate_limit_retry_mixin_spec.rb

The fix in e1b5c441c1658624184d3d8f924a3e9312485ed8 does not work every time. This is a much more simple approach that should work everytime.

DEV: Fix flaky test

---

app/jobs/scheduled/code_review_sync_repos.rb
app/models/github_repo_category.rb
spec/jobs/code_review_sync_repos_spec.rb

We're seeing a lot of:
```
Job exception: undefined method `[]' for nil:NilClass
```
in logs. This is related to [this line](https://github.com/discourse/discourse-code-review/blob/main/lib/discourse_code_review/source/github_pr_querier.rb#L535) in `GithubPRQuerier#associated_pull_requests`, where we expect data of the form:
```json
{
"data": {
"resource": {
"associatedPullRequests": {
"nodes": [],
"pageInfo": {
"endCursor": null,
"hasNextPage": false
}
}
}
}
}
```
but we're actually getting:
```json
{
"data": {
"resource": null
}
}
```
We currently iterate over known `GithubRepoCategory` records and schedule synchronisation for each.
When a repo is renamed, the old `GithubRepoCategory` remains, albeit with a `repo_id` that is null, alongside a new one. This causes a problem, as when we …

FIX: Stop trying to sync repositories that have moved

---

lib/discourse_code_review/source/github_pr_querier.rb
lib/discourse_code_review/source/github_pr_service.rb
spec/discourse_code_review/lib/github_pr_service_spec.rb

As part of synchronising repositories we look at associated pull requests of the commits in that repository. An assumption has been made here that those pull requests will belong to the same repository that we are synchronising.
This does not always hold true. In particular, when working with a forked repo and integrating upstream changes, the commits brought in may have associated pull requests from other repositories, causing synchronisation to fail because we can't find those pull requests.
This change correctly assigns the owner and name of pull requests that are associated with commits, and excludes pull requests from external repositories by default.
There are three levels of abstraction that could be chosen here, in order from high level to low: `GithubPRSyncer`, `GithubPRService`, …

FIX: Don't associate pull requests from other repositories

---

lib/discourse_code_review/state/github_repo_categories.rb

It used to fetch the first repository with no repo id associated.

FIX: Lookup by repo_id only when it exists

---

lib/discourse_code_review/github_repo.rb
lib/discourse_code_review/source/git_repo.rb
spec/discourse_code_review/lib/github_repo_spec.rb

Diff did not work for the first commit because "HASH^" was not a valid reference.

FIX: Allow diff with first commit

---

app/controllers/discourse_code_review/code_review_controller.rb
app/jobs/regular/code_review_sync_commits.rb
config/settings.yml
lib/discourse_code_review/github_pr_syncer.rb

We used this to find out why some reviews were skipped, but lately, it has been working more reliably so it is no longer necessary.

DEV: Remove code_review_debug site setting

---

lib/discourse_code_review/github_pr_poster.rb
spec/discourse_code_review/lib/importer_spec.rb

We have replaced the `#pluck_first` freedom patch with the native `#pick` in core [here](https://github.com/discourse/discourse/pull/19893).
This change is updates this plugin in the same fashion.

DEV: Replace #pluck_first monkey patch with native #pick

---

config/locales/server.en.yml
plugin.rb
spec/requests/discourse_code_review/list_controller_spec.rb

The approval topic lists used by the "Approval given" and "Approval pending" tabs on a user profile were always returning the approval topics created by the currently logged in user, not from the user of the profile we're currently viewing.
This PR fixes it by listing topics authored by the currently viewed `username` instead, meaning the mentioned tabs now show all Approval and Pending code reviews from commits created by the requested `username`, as expected.

FIX: approval topic lists should use username from route

---

config/locales/client.en.yml
config/settings.yml

This is so the plugins settings are better categorized in the site settings UI.

DEV: Change settings root from plugins: to discourse_code_review

---

lib/discourse_code_review/source/github_pr_querier.rb
spec/discourse_code_review/lib/github_pr_querier_spec.rb

We're seeing the following errors in production logs:
```
Job exception: undefined method `[]' for nil:NilClass
```
coming from here:
```
github_pr_querier.rb:449:in `block in associated_pull_requests'
```
It seems there's an assumption that the query here will always return a result, which doesn't seem to hold.
Break the assumption that there will be a response and properly handle the case where there's no resource.

FIX: Don't error out when no associated PRs found

---

spec/requests/discourse_code_review/code_review_controller_spec.rb

In https://github.com/discourse/discourse/pull/24740, `min_trust_to_create_topic` site setting was replaced by `create_topic_allowed_groups`. This PR replaces the former, deprecated one, with the latter.

DEV: Replace deprecated min_trust_to_create_post

---

assets/javascripts/discourse/initializers/init-code-review.js
spec/system/keyboard_shortcuts_spec.rb

This PR allows pressing “y” to approve a commit.

FEATURE: Add a keyboard shortcut to approve commits

---

spec/discourse_code_review/lib/github_pr_syncer_spec.rb
spec/discourse_code_review/lib/importer_spec.rb
spec/discourse_code_review/lib/state/commit_topics_spec.rb
spec/jobs/code_review_sync_commits_spec.rb
spec/requests/discourse_code_review/code_review_controller_spec.rb

We're updating core to change TL based access settings to be group based. This requires some updates of tests to work correctly. (The existing test setup gives false positives.)

DEV: Update test setup to work with auto groups

---

spec/requests/discourse_code_review/code_review_controller_spec.rb

Missed this one out, because the test is only run when `discourse-assign` is also present
Related: https://github.com/discourse/discourse/pull/24257

DEV: Add refresh_auto_groups to test where it was missed out

---

test/javascripts/acceptance/self-approve-mobile-test.js

In https://github.com/discourse/discourse/pull/30242, the topic footer buttons mobile dropdown can be replaced by the button if there's only one option.
This fixes the spec that was clicking on the dropdown button before checking there was no assign option.

DEV: fix mobile spec

---

assets/javascripts/discourse/initializers/init-code-review.js

This PR updates the deprecated `angle-double-right` icon name. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.

DEV: update deprecated icon name angle-double-right to angles-right

---

test/javascripts/acceptance/user-activity-approval-given-test.js
test/javascripts/acceptance/user-activity-approval-pending-test.js

Re-enables the tests disabled in https://github.com/discourse/discourse-code-review/commit/5a442d4393928f77c2a1723a98165b2b5417139d, now that https://github.com/discourse/discourse/pull/33455 has been merged

DEV: re-enable and update empty state test

---

lib/discourse_code_review/github_user_syncer.rb
spec/discourse_code_review/lib/github_user_syncer_spec.rb

internal ticket: t/122305/20
If staged users aren't allowed, use the system user when a real user doesn't match the commit.

FEATURE: don't create staged users if enable_staged_users is disabled
